### ISSUE TITLE
USER STORY: Create a recipie

### ISSUE THREAD

**Issue by sven-cork** [sven-cork/django-bakery-agile-project#1]
Epic: Recipie creation functionality 

As a **site user** I can **post recipies** so that **other users can enjoy my baking skills**. 

**Acceptance Criteria**:

- [ ] - Recipie form allows to enter title, category, ingredients and an image
- [ ] - After submitting form, the user is redirected to the recipie overview

**Tasks**:

- [ ] - Implement design of recipie form
- [ ] - Implement upload functionality
- [ ] - Include upload validation and error handling
- [ ] - Test functionality of creating and uploading a recipie
