### ISSUE TITLE
USER STORY: Account registration

### ISSUE THREAD

**Issue by sven-cork** [sven-cork/django-bakery-agile-project#2]
Epic: Register account for site

As a **site user** I can **register an account** so that **I can avail of all that Django Bakery has to offer**. 

**Acceptance Criteria**:

- [ ] - Allow to register an account based on email address
- [ ] - The user has access to all site tabs allowed for a registered user

**Tasks**:

- [ ] - Implement design to register form
- [ ] - Include form validation and error handling
- [ ] - Test account registration functionality
